@hostname=localhost
@port=8080

// generated using /login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjMDAxNzlmLWYzODgtNDNhYS1hN2M3LWFjNDI0YTkzMDNlMiIsImVtYWlsIjoiMTB4LmRldkBwYWZpbi5jb20iLCJuYW1lIjoiMTB4IGRldmVsb3BlciIsImlhdCI6MTY5MDcyODcxMiwiZXhwIjoxNjkwNzMwNTEyLCJhdWQiOiJhY2Nlc3MiLCJzdWIiOiIzYzAwMTc5Zi1mMzg4LTQzYWEtYTdjNy1hYzQyNGE5MzAzZTIifQ.ixib_Wv0Kci6r6OLJ0kkSuds9IfNLDr4Xo9sc1No06A

GET http://{{hostname}}:{{port}}/readyz

// Register
POST http://{{hostname}}:{{port}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "10x developer",
    "email": "10x.dev@pafin.com",
    "password": "P$ssW0Rd@123"
}


// Login
POST http://{{hostname}}:{{port}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "10x.dev@pafin.com",
    "password": "P$ssW0Rd@123"
}


// Profile
GET http://{{hostname}}:{{port}}/api/v1/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}

// Create User
POST http://{{hostname}}:{{port}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Jr. developer",
    "email": "jr@dev.com",
    "password": "P$ssW0Rd@123"
}

// List User
GET http://{{hostname}}:{{port}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

// GET user by ID
GET http://{{hostname}}:{{port}}/api/v1/users/f08e9dde-6a77-478c-b781-d33c5bb38e2c
Content-Type: application/json
Authorization: Bearer {{token}}


// Update user by ID
PATCH http://{{hostname}}:{{port}}/api/v1/users/f08e9dde-6a77-478c-b781-d33c5bb38e2c
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email":"sr.dev@pafin.com"
}

// DELETE user 
DELETE  http://{{hostname}}:{{port}}/api/v1/users/f08e9dde-6a77-478c-b781-d33c5bb38e2c
Content-Type: application/json
Authorization: Bearer {{token}}


