@hostname=localhost
@port=8080

// generated using /login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsa21zZmUzdjAwMDFvcnRxY2N3aXdkenUiLCJlbWFpbCI6ImRldkBwYWZpbi5jb20iLCJuYW1lIjoiMTB4IGRldmVsb3BlciIsImlhdCI6MTY5MDU2MTIzMSwiZXhwIjoxNjkwNTYzMDMxLCJhdWQiOiJhY2Nlc3MiLCJzdWIiOiJjbGttc2ZlM3YwMDAxb3J0cWNjd2l3ZHp1In0.wdi-5zXWSnOoX2HDB9o4pqjTr9lMvCluAHGGdfq-F4E

GET http://{{hostname}}:{{port}}/readyz

// Register
POST http://{{hostname}}:{{port}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "10x developer",
    "email": "dev@pafin.com",
    "password": "P$ssW0Rd@123"
}


// Login
POST http://{{hostname}}:{{port}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "dev@pafin.com",
    "password": "P$ssW0Rd@123"
}


// Profile
GET http://{{hostname}}:{{port}}/api/v1/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}

// Create User
POST http://{{hostname}}:{{port}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Jr. developer",
    "email": "jr.dev@pafin.com",
    "password": "P$ssW0Rd@123"
}

// List User
GET http://{{hostname}}:{{port}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

// GET user by ID
GET http://{{hostname}}:{{port}}/api/v1/users/clkmsf3iy0000ortqtj4iahe1
Content-Type: application/json
Authorization: Bearer {{token}}


// Update user by ID
PATCH http://{{hostname}}:{{port}}/api/v1/users/clkmsf3iy0000ortqtj4iahe1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email":"sr.dev@pafin.com"
}

// DELETE user 
DELETE  http://{{hostname}}:{{port}}/api/v1/users/clkmsf3iy0000ortqtj4iahe1
Content-Type: application/json
Authorization: Bearer {{token}}


