version: '3.8'

services:
  db:
    image: docker.io/bitnami/postgresql:15-debian-11
    restart: always
    environment:
      POSTGRESQL_USERNAME: pafin
      POSTGRESQL_PASSWORD: Pa$$word$123
      POSTGRESQL_DATABASE: dev
    healthcheck:
      test: pg_isready -d dev -U pafin
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres:/bitnami/postgresql
    networks:
      - pafin-net
  api:
    build:
      context: .
      target: dev
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    command:
      - /bin/sh
      - -c
      - |
        npx prisma db push --skip-generate 
        # npm run dev
        npm run start
    networks:
      - pafin-net
volumes:
  postgres:

networks:
  pafin-net:
    driver: bridge
