version: '3.8'

services:
  db:
    image: docker.io/bitnami/postgresql:15-debian-11
    restart: always
    environment:
      POSTGRESQL_USERNAME: pafin
      POSTGRESQL_PASSWORD: Password_123
      POSTGRESQL_DATABASE: dev
    healthcheck:
      test: pg_isready -d dev -U pafin
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres:/bitnami/postgresql
volumes:
  postgres:
