#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '-----------------------------------------------------------------------'
echo '-- 🏗️👷 Checking formats, testing and building your project before committing  --'
echo '-----------------------------------------------------------------------'

# Check Prettier standards
npm run check-format ||
    (

        echo '----------------------------------------------------------------------'
        echo '🤢😰 Prettier Check Failed. Run `npm run format`, add changes and try commit again.'
        echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        false
    )

# Check ESLint Standards
npm run check-lint ||
    (
        echo '----------------------------------------------------------------------'
        echo '🤯🥶 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        false
    )

# Check tsconfig standards
npm run check-types ||
    (
        echo '----------------------------------------------------------------------'
        echo '❌ Failed Type check. ❌
                Make the changes required above.'
        echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        false
    )

# If everything passes... Now we can commit
echo ' ------------------------------------------------------------'
echo '|        ✅✅✅✅ Yeppie, all test passed!!                     |'
echo '|        😁🤗 Begin comitting...... 👍👍                      |'